package ap_project_;
// Generated 28-May-2023 04:03:50 by Hibernate Tools 4.3.1



/**
 * Player generated by hbm2java
 */
public class Player  implements java.io.Serializable {


     private int pid;
     private String pname;
     private Integer page;
     private String password;
     private Integer pscore;
     private Integer plevel;

    public Player() {
    }

	
    public Player(int pid) {
        this.pid = pid;
    }
    public Player(int pid, String pname, Integer page, String password, Integer pscore, Integer plevel) {
       this.pid = pid;
       this.pname = pname;
       this.page = page;
       this.password = password;
       this.pscore = pscore;
       this.plevel = plevel;
    }
   
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }
    public Integer getPage() {
        return this.page;
    }
    
    public void setPage(Integer page) {
        this.page = page;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getPscore() {
        return this.pscore;
    }
    
    public void setPscore(Integer pscore) {
        this.pscore = pscore;
    }
    public Integer getPlevel() {
        return this.plevel;
    }
    
    public void setPlevel(Integer plevel) {
        this.plevel = plevel;
    }

    @Override
    public String toString() {
        return "Player{" + "pid=" + pid + ", pname=" + pname + ", page=" + page + ", password=" + password + ", pscore=" + pscore + ", plevel=" + plevel + '}';
    }



    

}


