package ap_project_;
// Generated 28-May-2023 04:03:50 by Hibernate Tools 4.3.1



/**
 * Study generated by hbm2java
 */
public class Study  implements java.io.Serializable {


     private StudyId id;
    // private Integer slevel;
     private Integer srate;
     private String scomment;

    public Study() {
    }

	
    public Study(StudyId id) {
        this.id = id;
    }
    public Study(StudyId id, Integer srate, String scomment) {
       this.id = id;
       this.srate = srate;
       this.scomment = scomment;
    }
   
    public StudyId getId() {
        return this.id;
    }
    
    public void setId(StudyId id) {
        this.id = id;
    }
    public Integer getSrate() {
        return this.srate;
    }
    
    public void setSrate(Integer srate) {
        this.srate = srate;
    }
    public String getScomment() {
        return this.scomment;
    }
    
    public void setScomment(String scomment) {
        this.scomment = scomment;
    }
    
    





}


