package ap_project_;
// Generated 28-May-2023 04:03:50 by Hibernate Tools 4.3.1



/**
 * StudyId generated by hbm2java
 */
public class StudyId  implements java.io.Serializable {


     private int pid;
     private int slevel;

    public StudyId() {
    }

    public StudyId(int pid, int slevel) {
       this.pid = pid;
       this.slevel = slevel;
    }
   
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    public int getSlevel() {
        return this.slevel;
    }
    
    public void setSlevel(int slevel) {
        this.slevel = slevel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudyId) ) return false;
		 StudyId castOther = ( StudyId ) other; 
         
		 return (this.getPid()==castOther.getPid())
 && (this.getSlevel()==castOther.getSlevel());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPid();
         result = 37 * result + this.getSlevel();
         return result;
   }   


}


